// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AFP_WEBAPI_PRUEBA.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AFP_WEBAPI_PRUEBA.Data
{
    public partial interface IPRUEBA_AFPContextProcedures
    {
        Task<List<GET_DEPARTAMENTOSResult>> GET_DEPARTAMENTOSAsync(int? EMPRESAID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GET_EMPRESAResult>> GET_EMPRESAAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
