// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AFP_WEBAPI_PRUEBA.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AFP_WEBAPI_PRUEBA.Data
{
    public partial class PRUEBA_AFPContext
    {
        private IPRUEBA_AFPContextProcedures _procedures;

        public virtual IPRUEBA_AFPContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new PRUEBA_AFPContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IPRUEBA_AFPContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GET_DEPARTAMENTOSResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<GET_EMPRESAResult>().HasNoKey().ToView(null);
        }
    }

    public partial class PRUEBA_AFPContextProcedures : IPRUEBA_AFPContextProcedures
    {
        private readonly PRUEBA_AFPContext _context;

        public PRUEBA_AFPContextProcedures(PRUEBA_AFPContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GET_DEPARTAMENTOSResult>> GET_DEPARTAMENTOSAsync(int? EMPRESAID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "EMPRESA_ID",
                    Value = EMPRESAID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GET_DEPARTAMENTOSResult>("EXEC @returnValue = [dbo].[GET_DEPARTAMENTOS] @EMPRESA_ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<GET_EMPRESAResult>> GET_EMPRESAAsync(int? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GET_EMPRESAResult>("EXEC @returnValue = [dbo].[GET_EMPRESA] @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
