// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AFP_WEBAPI_PRUEBA.Models;
using Microsoft.EntityFrameworkCore;

namespace AFP_WEBAPI_PRUEBA.Data;

public partial class PRUEBA_AFPContext : DbContext
{
    public PRUEBA_AFPContext(DbContextOptions<PRUEBA_AFPContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Departamento> Departamento { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DEPARTAM__3214EC2757B8345E");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Empresa).WithMany(p => p.Departamento).HasConstraintName("FK__DEPARTAME__EMPRE__276EDEB3");
        });

        modelBuilder.Entity<Empresa>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EMPRESA__3214EC273260C5BC");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}