// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AFP_WEBAPI_PRUEBA.Models;

[Table("DEPARTAMENTO")]
public partial class Departamento
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NOMBRE")]
    [StringLength(300)]
    public string Nombre { get; set; }

    [Column("NUMERO_EMPLEADOS")]
    public int NumeroEmpleados { get; set; }

    [Required]
    [Column("NIVEL_ORGANIZACION")]
    [StringLength(300)]
    public string NivelOrganizacion { get; set; }

    [Column("EMPRESA_ID")]
    public int? EmpresaId { get; set; }

    [ForeignKey("EmpresaId")]
    [InverseProperty("Departamento")]
    public virtual Empresa Empresa { get; set; }
}