// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AFP_WEBAPI_PRUEBA.Models
{
    public partial class GET_EMPRESAResult
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string RAZON { get; set; }
        public DateTime? FECHA_REGISTRO { get; set; }
        public DateTime? FECHA_CREACION { get; set; }
        public string USR_CREACION { get; set; }
    }
}
