// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AFP_WEBAPI_PRUEBA.Models
{
    public partial class GET_DEPARTAMENTOSResult
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public int NUMERO_EMPLEADOS { get; set; }
        public string NIVEL_ORGANIZACION { get; set; }
    }
}
